"""Agent strategies and the foundational ``Agent`` / ``Tool`` / ``SystemPromptBuilder`` primitives.

Houses the long tail of agent strategies (ReAct, ReWOO, Reflexion, LATS, Tree-of-Thought,
CodeAct, Reasoning) alongside the base primitives every strategy depends on.
"""

from nanitics.strategies.agents import (
    ActionNode,
    Agent,
    AgentInput,
    AgentResult,
    BoundAgent,
    CodeActAgent,
    ContextContent,
    ContextManagement,
    ContextProvider,
    ErrorHandling,
    EvaluationCheck,
    EvaluationContext,
    EvaluationResult,
    EvaluationVerdict,
    LATSAgent,
    OutputEvaluator,
    ReActAgent,
    ReasoningAgent,
    ReflexionAgent,
    ReWOOAgent,
    ReWOOPlan,
    ReWOOStep,
    SearchStrategy,
    ThoughtNode,
    TreeOfThoughtAgent,
    WorkingMemory,
    WorkingMemoryContributor,
)
from nanitics.strategies.prompts import SystemPromptBuilder, SystemPromptContributor
from nanitics.strategies.tools import (
    ConditionalTool,
    FunctionTool,
    Tool,
    ToolContext,
    ToolRegistry,
    ToolResult,
    tool,
)

__all__ = [
    "ActionNode",
    "Agent",
    "AgentInput",
    "AgentResult",
    "BoundAgent",
    "CodeActAgent",
    "ConditionalTool",
    "ContextContent",
    "ContextManagement",
    "ContextProvider",
    "ErrorHandling",
    "EvaluationCheck",
    "EvaluationContext",
    "EvaluationResult",
    "EvaluationVerdict",
    "FunctionTool",
    "LATSAgent",
    "OutputEvaluator",
    "ReActAgent",
    "ReWOOAgent",
    "ReWOOPlan",
    "ReWOOStep",
    "ReasoningAgent",
    "ReflexionAgent",
    "SearchStrategy",
    "SystemPromptBuilder",
    "SystemPromptContributor",
    "ThoughtNode",
    "Tool",
    "ToolContext",
    "ToolRegistry",
    "ToolResult",
    "TreeOfThoughtAgent",
    "WorkingMemory",
    "WorkingMemoryContributor",
    "tool",
]
