"""Error classes and the error-handling capability surface."""

from nanitics.capabilities.errors import (
    ErrorCategory,
    ErrorClassifier,
    ErrorHandler,
    RetryPolicy,
    classify_error,
    format_correction_prompt,
)
from nanitics.collaboration.hitl_store import (
    DuplicateHitlRequestError,
    DuplicateHitlResponseError,
)
from nanitics.composition.durability.models import CheckpointVersionError
from nanitics.composition.multi_agent.peer_network import PeerBudgetExceededError
from nanitics.composition.orchestration.pipeline import PipelineContractError
from nanitics.composition.orchestration.workflow import WorkflowCancelledError
from nanitics.infrastructure.errors import (
    AgentBudgetExceededError,
    AgentError,
    AgentEscalationError,
    AgentIterationLimitError,
    AgentToolCallLimitError,
    ApprovalTimeoutError,
    ApprovalUnavailableError,
    EmbeddingError,
    EmbeddingProviderError,
    EmbeddingRateLimitError,
    HumanInputProviderError,
    LLMAuthenticationError,
    LLMContextLengthError,
    LLMError,
    LLMOverloadedError,
    LLMProviderError,
    LLMQuotaExhaustedError,
    LLMRateLimitError,
    LLMSchemaViolationError,
    MCPAuthError,
    NaniticsError,
    ThreadInUseError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolParameterError,
    ToolResultTooLargeError,
    ToolTimeoutError,
)
from nanitics.infrastructure.observability import MalformedStoredEventError
from nanitics.safety.cancellable_dispatch import RunCancelled

__all__ = [
    "AgentBudgetExceededError",
    "AgentError",
    "AgentEscalationError",
    "AgentIterationLimitError",
    "AgentToolCallLimitError",
    "ApprovalTimeoutError",
    "ApprovalUnavailableError",
    "CheckpointVersionError",
    "DuplicateHitlRequestError",
    "DuplicateHitlResponseError",
    "EmbeddingError",
    "EmbeddingProviderError",
    "EmbeddingRateLimitError",
    "ErrorCategory",
    "ErrorClassifier",
    "ErrorHandler",
    "HumanInputProviderError",
    "LLMAuthenticationError",
    "LLMContextLengthError",
    "LLMError",
    "LLMOverloadedError",
    "LLMProviderError",
    "LLMQuotaExhaustedError",
    "LLMRateLimitError",
    "LLMSchemaViolationError",
    "MCPAuthError",
    "MalformedStoredEventError",
    "NaniticsError",
    "PeerBudgetExceededError",
    "PipelineContractError",
    "RetryPolicy",
    "RunCancelled",
    "ThreadInUseError",
    "ToolError",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ToolParameterError",
    "ToolResultTooLargeError",
    "ToolTimeoutError",
    "WorkflowCancelledError",
    "classify_error",
    "format_correction_prompt",
]
